### ISSUE TITLE
Re-integrate github login link properly with the theme

### ISSUE THREAD

**Issue by samueldr** [nixos-users/wiki#11]
See #7,

The github login link comes from an extension that has almost no facilities to customize the behaviour.

There will be a bit of integration to do with the mediawiki extensions system and the chosen theme.

### Current state

The login link is a static link added to the nav bar.

### What it needs to do

  * Redirects user back on the right page when logged-in.
  * Not be present when logged-in.
  * Navbar should not overflow at any width.

Furthermore

  * Both login elements (github and user/pw) should always be present when one is present.

**Comment by samueldr** [comment]
This is now complete.

 * https://gitlab.com/samueldr/nixos-wiki-proposition/commit/07c0dfde9aa8a22297c8272fa0dd0e222e115222

### Changes in the wiki special pages

`MediaWiki:Tweeki-navbar-right`

```
TOOLBOX,NIXOS-LOGIN-PROFILE,SEARCH
```

### Additional proposed changes

With this fix:

 * https://gitlab.com/samueldr/nixos-wiki-proposition/commit/a36b00c80302f97d26a5d197eb2caac6e38f6b66

Adding the edit link and the profile/login item to the footer.

`MediaWiki:Tweeki-footer`

```
FOOTER,EDIT,NIXOS-LOGIN-PROFILE
```

**Comment by fadenb** [comment]
Applied changes
