### ISSUE TITLE
Make actions toolbox available...

### ISSUE THREAD

**Issue by samueldr** [nixos-users/wiki#14]
It *should* have been available on the edit button (`EDIT-EXT`), [according to the theme documentation](http://tweeki.thai-land.at/wiki/Navigation).

This needs investigation.

In the meantime, `ACTIONS` could be added to the `MediaWiki:Tweeki-sidebar-right` page.

**Comment by samueldr** [comment]
```
diff --git a/config.php b/config.php
index 176c80d..b40576b 100644
--- a/config.php
+++ b/config.php
@@ -92,6 +92,8 @@ $wgResourceModules["x.nixos-wiki.styles"] = array(
 // and personal links for editors) for anonymous users
 $wgTweekiSkinHideAnon["EDIT-EXT"] = true;  
 $wgTweekiSkinHideAnon["subnav"] = true;
+// Always show the combined edit/actions button.
+$wgTweekiSkinHideNonAdvanced = ["EDIT-EXT-special" => false];
 $wgTweekiSkinHideable[] = "sidebar-right"; 
 $wgTweekiSkinHideable[] = "firstHeading"; 
 $wgTweekiSkinUseBtnParser = false;
```

https://gitlab.com/samueldr/nixos-wiki-proposition/commit/f5289eff28c2996350c170b8add83ec72e94ba35

Close the issue once it's been implemented upstream please!

**Comment by samueldr** [comment]
![20171007125416](https://user-images.githubusercontent.com/132835/31310031-a71e8882-ab5e-11e7-8f8d-d26db4e074dd.png)

This would be the result, allowing users to do what the different navigational elements did on the Vector (default) theme.

**Comment by fadenb** [comment]
Applied changes, working fine :+1:
