### ISSUE TITLE
File:* pages aren't working as expected

### ISSUE THREAD

**Issue by samueldr** [nixos-users/wiki#15]
Right now, anything, anything ending in some common filename patterns are not handled correcly by nginx.

* https://nixos.wiki/wiki/File:Home-news.png
* (page does not exist, but issue is independent from the wiki) https://nixos.wiki/wiki/Optipng

This makes it way harder to replace an existing file. It also makes it impossible to view the metadata of a file.

**Comment by fadenb** [comment]
Issue has been fixed. File pages are now accessible, e.g. https://nixos.wiki/wiki/File:Nixos-stack2.png 
A try_files directive was missing in the block matching file extensions
