### ISSUE TITLE
Add talk links to the theme

### ISSUE THREAD

**Issue by samueldr** [nixos-users/wiki#18]
This is a theme issue, afaik, I'll need to look into it.

There is no way to access a `$NAMESPACE Talk:$PAGE` page right now.

**Comment by samueldr** [comment]
There is nothing to change in either the wiki or the configuration, it can all be done through the theme configuration with the MediaWiki special pages.

## Adding to the right sidebar

Change `MediaWiki:Tweeki-footer` from (default):

```
EDIT-EXT,TOC
```

to:

```
EDIT-EXT,TALK,TOC
```

![20171022164521](https://user-images.githubusercontent.com/132835/31866121-743c276c-b748-11e7-85e1-371154bc3438.png)


## Adding to the footer

Change `MediaWiki:Tweeki-footer` from:

```
FOOTER,EDIT,NIXOS-LOGIN-PROFILE
```

to:

```
FOOTER,EDIT,TALK,NIXOS-LOGIN-PROFILE
```

![20171022164534](https://user-images.githubusercontent.com/132835/31866122-7a107d96-b748-11e7-8763-a6e943f9bca1.png)

**Comment by fadenb** [comment]
@samueldr I believe some tweeki page names got confused. I edited your post accordingly (`MediaWiki:Tweeki-sidebar-right` instead of `MediaWiki:Tweeki-footer` for both changes).

Changes applied.
