### ISSUE TITLE
GTK dark theme makes text editing section almost unreadable

### ISSUE THREAD

**Issue by Infinisil** [nixos-users/wiki#20]
Here is a screenshot of what I mean:
![image](https://user-images.githubusercontent.com/20525370/33235522-163439ea-d23a-11e7-9408-1f3993979049.png)

**Comment by Infinisil** [comment]
This is nothing specifically wrong with the wiki I found out, happens with lots of places, the problem is either firefox or my gtk theme (happens with all dark ones for some reason).

**Comment by samueldr** [comment]
Hey now, I only forgot about this!

I have (just now) added a CSS rule for textual inputs and textareas so it forces a background color; a website should either use ALL defaults or NO defaults. That theme used defaults only for input controls, which (probably) caused the issue.
