### ISSUE TITLE
How to switch to the classic Mediawiki theme?

### ISSUE THREAD

**Issue by volth** [nixos-users/wiki#26]
It there a possibility to switch to the classic Mediawiki theme?
Such as one on Wikipedia, EncyclopediaDramatica, Lurkmore and other websites?
Maybe something in user preferences or by setting some cookie?

Being accustomed to view and edit the classic theme for so many years it is very unconvenient to use the current nixos.wiki theme

**Comment by Mic92** [comment]
If you login as a user, you can set the theme in your personal preferences.
However note that we do not support this theme or test, if our wiki plugins work all correctly with the stock wiki theme: https://dl.thalheim.io/Vd_Gf5vOVQ2H_g_-53-SDg/2018-01-07.vkuux.png
