### ISSUE TITLE
Reorganizing the Wiki for improved UX

### ISSUE THREAD

**Issue by ixxie** [nixos-users/wiki#3]
I have been thinking about how to improve navigation and UX in the wiki. I already added a little sidebar with some important pages, which I believe helps. I think the next step is to create a clear *skeleton* for the wiki to help direct newcomers (and contributors) to where they need to be. 

Now, the following ended up a bit longer than I had hoped, so apologies for that. In any case, I thought that such a drastic plan should be discussed before being implemented. Once - on this thread - we agree about the structural map, I could start another issue with a checklist and we can divide the work.

Now since the wiki is to be complementary to the manual, rather than a replacement, I figured we should also think about *how is the wiki going to be different*. The following is what I could come up with:

1. **Ecosystemic**: the manuals cover specific software (Nix, NixOS, etc.) while the wiki covers the Nix ecosystem as a whole, helping the user understand the interrelations more clearly.
2. **Heterogeneous**: the manuals normally give one canonical approach to something, the wiki has the potential to reveal the more diverse approaches and workflows used in practice.
3. **Pragmatic**: the manuals are intended for comprehensive and detailed reference, while the wiki could emphasize practical and learning resources such as guides, tutorials and cookbooks.
4. **Reticulate**: the manuals are *catenary* meaning they have a linear sequence of one chapter following another while the wiki is *reticulate*, having a network structure of links, allowing the user to reach information in multiple ways.
5. **Community**: the manuals cover the more official and stable core of the Nix ecosystem, while the wiki can cover the whole Nix community with its diverse projects and communication channels.

Based on these considerations, I propose the following two-tiered structure for the skeleton and navigation sidebar; the links / pages are marked in bold and the explanation of the page contents in italics:

* **Home Page** - *Gives a general introduction to the wiki and a map of its contents.*

* **Search** - *Links to the hound search tool as it does now.*

* **Ecosystem** - *An article providing an overview of the components of the Nix ecosystem and their relations, including everything listed below. Possible also with infographics.*
   - **NixOS***
   - **Nix***
   - **Nixpkgs** - *An overview of how nixpkgs is arranged, and how its development workflow goes.*
   - **Nix Language** - *An overview of the language, usage, design patterns (linked to cookbooks).*
   - **NixOps***
   - **Hydra***
   - **Disnix***
   - **Other Applications** - *This is the page now called 'Applications' which will be renamed for clarity in this context; maybe another name would be better.*

* **Resources** -  *This is to provide an overview of helpful resources for learning and using Nix/OS stuff, including the whole contents of what is now the 'Bookmarks' page.*
    - **Guides** - *How-to guides: for example installation, language and hardware specific guides.*
    - **Tutorials** - *Pedagogic courses: specifically designed to teach some aspect of the ecosystem.*
    - **Cookbooks** - *Recipe collections: arranged by theme / tool in separate articles.*

* **Community** - *An overview of the Nix/OS community, IRC, Github, Reddit, etc.*
    - **Contribute** - *A contribution guide, for the wiki, the Nix ecosystem and the community in general.*
    - **Support** - *Where to get help, including links to troubleshooting guides, the FAQ, etc.*

[* for the NixOS, Nix, NixOps, Hydra and Disnix pages it would be nice to have a regular structure - something like *introduction*, *usage* (installation, operation, configuration), *internals*, *development* and (optionally) *history*.]

So what do you folks think?

**Comment by Mic92** [comment]
I largely agree with the structure. The only thing which seems ambiguous to me, is how to distinguish between guides, tutorials and cookbooks. The arch wiki equivalent to this section is probably https://wiki.archlinux.org/index.php/General_recommendations
I would propose to flatten the hierarchy here for the sake of simplicity.

**Comment by ixxie** [comment]
In my understanding, *guides* are longer instructional texts that help you accomplish a particular task (installation, getting, *tutorials* are educational tours intended to teach you something, and *cookbooks* are collections of short hacks / code snippets arranged around a theme.

I agree that at this point, we are probably lacking the content to warrant these three to have their own pages; this may also apply to some other pages. For these, we can have subsections in the parent page in the meanwhile.

I would still like to have a way to focus contributions on these resources, but we can figure it out after this initial skeleton is built.

**Comment by makefu** [comment]
@ixxie I really like the new structure and i am pretty sure this change can make a difference with regards to the sub-par documentation for the nix ecosystem right now.

I am in favor of distinguishing between tutorials and HOW-TOs.
* Tutorials are learning-oriented and especially helpful for newcomers.
* How-Tos solve real-world problems and are goal-oriented.

@Mic92 a very good read is https://www.divio.com/en/blog/documentation/ . It explains the difference between the types of documentation. It also somewhat depicts the biggest issue with the nix* manuals: different types of documentation get mixed up into multiple large documents.

**Comment by vyp** [comment]
@makefu Yep so just clarifying, How-Tos = Guides as @ixxie and your link says.

**Comment by makefu** [comment]
@vyp exactly. But as ixxie said, as long as we do not have enough resources to fill up whole pages we can keep them on a single page. In the end it is a wiki and stuff can change over time.

**Comment by ixxie** [comment]
@makefu that link is great! Exactly what I had in mind. I guess the ecosystem articles would fall under both reference and discussion, but where the documentations are (or should be) more reference like, the wiki would be more discussion like. The one thing missing from there is the cookbook, which is a bit different.

**Comment by Mic92** [comment]
Summarized here: https://nixos.wiki/index.php?title=Contributing_to_to_the_wiki&diff=251&oldid=0
