### ISSUE TITLE
Difference between Nix and Nix Language in sitemap

### ISSUE THREAD

**Issue by Mic92** [nixos-users/wiki#4]
At the moment I don't see a significant difference between both.
So either a summary should be added, what each part should contain or I would suggest to merge both into one section.

**Comment by ixxie** [comment]
@Mic92 - Nix Language would cover the Nix Expression Language in the way programming languages are normally introduced. Nix would cover the Nix Package Manager in the way package managers are usually introduced, focusing on usage, internals and configuration. 

I think the lack of a distinct handling of these two is one of the reasons the whole ecosystem is a bit confusing to newcomers.

**Comment by ixxie** [comment]
I will add the summary.

**Comment by ixxie** [comment]
I put this:

Nix: "This discussion article is to cover the usage, internals and configuration of the Nix package manager."

Nix Language: "This discussion article covers the syntax, semantics, typing, compilation, tooling and libraries of the Nix Expression Language."

I tried to change the Nix entry in the sidebar to Nix Package Manager (the full name of the article it links to) but it make the link two lines, so I reverted it. I think its quite clear like this.

**Comment by Mic92** [comment]
ok.
