### ISSUE TITLE
Where to raise issues / discuss the wiki?

### ISSUE THREAD

**Issue by ixxie** [nixos-users/wiki#6]
Are we planning to keep using Github to discuss wiki issues? It seems like a great solution because I never did understand how mediawiki talk pages are supposed to be used (you can see my attempt on the [main page talk](https://nixos.wiki/wiki/Talk:Main_Page).

Perhaps some combination of Github and Mediawiki is in order?

**Comment by Mic92** [comment]
Yes, mediawiki discussions can become pretty messy. They are maybe ok-ish to discuss some small parts of an article. But they are not so great for larger problems/discussions regarding wiki or the infrastructure.

**Comment by ixxie** [comment]
I suggest we treat the talk pages as 'to do lists' associated with the article, or sometimes with more general things (e.g. the main page as a todo list for the whole wiki, the category metapages as strategic todo lists for those categories, etc.).
