### ISSUE TITLE
Theme situation / discussion

### ISSUE THREAD

**Issue by samueldr** [nixos-users/wiki#7]
Hi,

As stated on `#nixos-wiki`, I worked a bit on the theme situation.

There is nothing tangible to show, except screenshots. I am currently using a bitnami VM to play around with mediawiki, while waiting for the configuration of the current wiki to be made available. (I do not know how to setup mediawiki with NixOS.)

> The red border on those screenshots are my WM theme

![20170912225002](https://user-images.githubusercontent.com/132835/30357483-cdbbf00c-980c-11e7-8f67-f2ab8bca8e26.png)

![20170912224950](https://user-images.githubusercontent.com/132835/30357476-ca301760-980c-11e7-840b-23a8d0f3b89c.png)

### What's done

- [x] Basic themeing
- [x] Initial customization

#### Basic theming

A base theme was picked, [Tweeki (website and demo)](http://tweeki.thai-land.at/wiki/Welcome).

This theme was picked as a starting point. It is the rough rock that we need to work out to be pretty.

An important point is that no customization has to be made by modifying the skin's files. This is to allow updating the skin as updates are released. Though, if/when we will outgrow the capabilities of the skin we will invest into keeping it up to date.

> ##### Why bootstrap based?
>
> This can help democratize the development for the styles and themeing of the wiki.
> It was also chosen since the NixOS website is based on bootstrap. This allows
> us to make the wiki look like the website.

#### Initial customization

I have backported the original bootstrap navbar to that updated bootstrap, making it pretty much 1:1 with the nixos website's navbar. It is all done through CSS.

The TOC has been made permanently open. The default behaviour of Tweeki, taken from bootstrap is annoying.

### What needs to be done

- [x] More customization
- [x] Code audit
- [x] Public configuration for the wiki
- [ ] Templates adjustments
- [x] Cleanup and proper pull request for skin
- [x] Implementation notes
- [ ] Github login link support

#### More customization

There are some aspects of the Tweeki theme that I dislike, some that are really opinionated. They do not affect the actual use of the wiki.

- [x] Add logo to top bar
- [x] Fill-in the top bar
- [x] When hiding TOC, use full width

#### Code audit

I do not believe there is anything malicious in the selected base theme, but I do not know what is the quality of the code. Could there be anything that would expose the wiki or wiki users to XSS or other attacks? This needs to be checked.

#### Public configuration for the wiki

When the configuration will be available, I will be able to integrate the wiki theme configuration properly with the deploy process. I do not want nor do I expect anyone to do the integration bit.

(See #8 for the configuration I currently am using)

#### Templates adjustments

The templates I created *are not as independent as I thought*. There is one in particular that was pretty dependent on Vector's (default theme) metrics.

This brings up a question **if we have a custom theme, should we disable other themes**?

> My opinion is that we should, if we want to profit from themeing fully. Otherwise, we have to ensure that every customization bit works across all enabled themes.

#### Implementation notes

I realized that I forgot to note a couple of points for when we'll integrate the theme:

  * Some settings are special mediawiki pages, just like how the sidebar works
      * tweeki-navbar-left, which provides link at the top

#### Github login link

*This needs investigating.* Tweeki, with default settings, seems to not render a particular location where the extension hooks.

**Comment by makefu** [comment]
I'd really love to see a custom theme to be applied , especially when it provides a mobile mode (which it apparently does). 
Additionally with this theme the wiki matches the main page https://nixos.org .

What we might need as a modification is a sidebar on the left with our Category bookmarks.

@fadenb can you copy the current wiki configuration somewhere? maybe even directly in this repository, i provide you access.

I will try to perform a code review of the theme today or tomorrow.

**Comment by Mic92** [comment]
+1 for disabling the other themes - less maintenance.

**Comment by makefu** [comment]
Together with @Mic92 we've performed a very short code review and based on the code the author of the skin has at least some basic understanding that escaping is necessary in the application.
There were at least no obvious code injection or XSS vulnerabilities in the code.

I however have not done some dynamic tests with user input yet.

I also agree with removing all other themes.

**Comment by samueldr** [comment]
![20170923200942](https://user-images.githubusercontent.com/132835/30778129-5391f3ca-a09b-11e7-9a99-8a676fbadd8e.png)

It's progressing.

I had a discussion with @fadenb on IRC a week ago, there were some issues he pointed out with the theme. Those that were bugs of my doing (TOC scrollbar) are fixed.

There's still one pain point with the theme; the theme isn't fluid like the default wiki theme.

This makes some pages' problems more obvious, like the [cheat sheet](https://nixos.wiki/wiki/Cheatsheet) where the table isn't pretty. (Though, it already presents some problems). That particular page is an issue in and of itself since a table isn't the best way to provide informations like the cheat sheet does. The page probably will need a revamp with sections.

There's only a handful of things left for me to be entirely fine with publishing the theme and customizations. They all revolve around the templates. I'll verify they all are fine, and then I'll provide a configuration that can be tracked for the current state.

I'll be opening another issue, with regards to the public configuration of the wiki.

**Comment by samueldr** [comment]
Tweeki settings set in special pages

  * `MediaWiki:Tweeki-navbar-left`
```
Ecosystem
* Nix Ecosystem|Overview
* NixOS|NixOS
* Nix Package Manager|Nix
* Nix Expression Language|Nix Language
* Nixpkgs|Nixpkgs
* NixOps|NixOps
* Hydra|Hydra
* Applications|Applications
Resources
* Bookmarks|Bookmarks
* Category:Guide|Guides
* Category:Tutorial|Tutorials
* Category:Discussion|Discussions
* Category:Reference|Reference
* Category:Cookbook|Cookbooks
Community
* Nix Community|About
* Get Involved|Get Involved
* Support|Support
Wiki
* Contributing to the wiki|Contribute
* Wiki Projects|Projects
* recentchanges-url|recentchanges
* randompage-url|randompage
* https://www.mediawiki.org/wiki/Special:MyLanguage/Help:Contents|Help
```

**Comment by ixxie** [comment]
Great work @samueldr ! It really looks amazing!

**Comment by samueldr** [comment]
*Closing the long-standing issue in favor of #11*
